apiVersion: apps/v1
kind: Deployment
metadata:
  name: planes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planes
  template:
    metadata:
      labels:
        app: planes
    spec:
      restartPolicy: Always
      containers:
        - image: planes_image:v02
          imagePullPolicy: Never
          name: planes-app
          env:
            - name: DB_HOST
              value: 10.97.11.82
            - name: DB_NAME
              value: planes1
            - name: DB_PASSWORD
              value: "12346"
            - name: DB_USER
              value: postgres
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8080