apiVersion: v1
kind: Service
metadata:
  name: planes
  labels:
    app: planes
spec:
  type: NodePort
  selector:
    app: planes
  ports:
    - name: planes
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP